name: Release
on: 
  push:
    branches: 
      - master
jobs:
  unit-test:
    runs-on: ubuntu-16.04
    env:
      working-directory: ./build/src
      CI: true
    name: Unit Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}
      - name: yarn lint
        run: yarn lint
        working-directory: ${{ env.working-directory }}
      - name: yarn test
        run: yarn test
        working-directory: ${{ env.working-directory }}  
  it-test:
    runs-on: ubuntu-16.04
    env:
      working-directory: ./build/src
      CI: true
    name: In app integration tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}
      - name: yarn test:int
        run: yarn test:int
        working-directory: ${{ env.working-directory }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [unit-test,it-test]
    env:
      TRAVIS: yes
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: dappnodesdk install
        run: npm install -g @dappnode/dappnodesdk
      - name: Docker-Compose Build
        run: docker-compose build
      - name: publish
        run: dappnodesdk publish patch --dappnode_team_preset --provider infura
